# Generated by Django 4.2.10 on 2024-02-08 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(default=datetime.datetime(2024, 2, 15, 18, 25, 26, 220017, tzinfo=datetime.timezone.utc), null=True)),
                ('public', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baseimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
