# Generated by Django 4.2.10 on 2024-02-08 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomimage',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 18, 25, 39, 674168, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
