# Generated by Django 4.2.10 on 2024-02-08 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_showroomimage_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomimage',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 2, 49, 197743, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
