# Generated by Django 4.2.10 on 2024-02-08 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateField(default=datetime.datetime(2023, 10, 19, 18, 25, 26, 219202, tzinfo=datetime.timezone.utc))),
                ('finished_at', models.DateField(default=django.utils.timezone.now)),
                ('width', models.SmallIntegerField()),
                ('height', models.SmallIntegerField()),
                ('available_to_buy', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=500.0, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Base Image',
                'verbose_name_plural': 'Base Images',
                'db_table': 'images_base_image',
            },
        ),
        migrations.CreateModel(
            name='BuyerPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Buyer Persona',
                'db_table': 'images_buyer_persona',
            },
        ),
        migrations.CreateModel(
            name='ImageMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=5000)),
            ],
            options={
                'verbose_name': 'Medium',
                'verbose_name_plural': 'Mediums',
                'db_table': 'images_medium',
            },
        ),
        migrations.CreateModel(
            name='ImagePaintingSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseImageMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baseimage')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagemedium')),
            ],
            options={
                'verbose_name': 'Image Medium',
                'db_table': 'images_base_image_medium',
            },
        ),
        migrations.CreateModel(
            name='BaseImageBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('can_be_named', models.BooleanField(default=False)),
                ('buyer_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.buyerpersona')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.baseimage')),
            ],
            options={
                'verbose_name': 'Image Buyer',
                'db_table': 'images_image_buyer',
            },
        ),
        migrations.AddField(
            model_name='baseimage',
            name='medium',
            field=models.ManyToManyField(related_name='base_images', through='core.BaseImageMedium', to='core.imagemedium'),
        ),
        migrations.AddField(
            model_name='baseimage',
            name='painting_surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagepaintingsurface'),
        ),
        migrations.AddField(
            model_name='baseimage',
            name='transactions',
            field=models.ManyToManyField(through='core.BaseImageBuyer', to='core.buyerpersona'),
        ),
    ]
