# Generated by Django 4.2.10 on 2024-02-08 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseimage',
            name='started_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 19, 18, 25, 39, 673317, tzinfo=datetime.timezone.utc)),
        ),
    ]
